// This file is @generated by prost-build.
/// A representation of the state of an inner-backend -- a backend that's a part of the multi-backend.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InnerBackendCommit {
    /// The commit ID of the inner backend.
    #[prost(bytes = "vec", tag = "1")]
    pub commit_id: ::prost::alloc::vec::Vec<u8>,
    /// The path to the inner backend.
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    /// Whether the repo or backend at this path is already deleted.
    #[prost(bool, tag = "3")]
    pub deleted: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LabeledMergeTrees {
    #[prost(bytes = "vec", tag = "1")]
    pub tree_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub conflict_label: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Timestamp {
    #[prost(int64, tag = "1")]
    pub millis_since_epoch: i64,
    #[prost(int32, tag = "2")]
    pub tz_offset: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Commit {
    /// The current commit's ID.
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    /// The commit IDs from all the member backends.
    #[prost(message, repeated, tag = "2")]
    pub inner_backend_commits: ::prost::alloc::vec::Vec<InnerBackendCommit>,
    /// The parent commits.
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub parent_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// The ancestral commits.
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub predecessor_ids: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, tag = "5")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub author_name: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub author_email: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub author_timestamp: ::core::option::Option<Timestamp>,
    #[prost(string, tag = "9")]
    pub committer_name: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub committer_email: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "11")]
    pub committer_timestamp: ::core::option::Option<Timestamp>,
    /// TODO: does this really work? One change ID to many commits?
    #[prost(bytes = "vec", tag = "12")]
    pub change_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "13")]
    pub merge_data: ::prost::alloc::vec::Vec<LabeledMergeTrees>,
}
