// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MultiBackendPaths {
    /// Paths to inner backends.
    #[prost(map = "string, string", tag = "1")]
    pub repo_to_store_path_map: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
