// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InnerBackendTreeId {
    #[prost(bytes = "vec", tag = "1")]
    pub tree_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    /// Whether the sub-tree at the `tree_id` above is a tree in the multi-backend
    /// or in one of the encapsulated backends.
    #[prost(bool, tag = "3")]
    pub is_tree_multi_backend: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TreeIds {
    #[prost(bytes = "vec", tag = "1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    /// Inner backend IDs.
    #[prost(message, repeated, tag = "2")]
    pub inner_trees: ::prost::alloc::vec::Vec<InnerBackendTreeId>,
    #[prost(string, tag = "3")]
    pub root_path: ::prost::alloc::string::String,
}
