// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InnerBackendTreeId {
    #[prost(bytes = "vec", tag = "1")]
    pub tree_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TreeIds {
    #[prost(int64, tag = "1")]
    pub id: i64,
    /// Inner backend IDs.
    #[prost(message, repeated, tag = "2")]
    pub inner_trees: ::prost::alloc::vec::Vec<InnerBackendTreeId>,
}
